name: Code checks

on:
  push:
    branches: [ main ]
  pull_request: null

jobs:
  ecs:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        php: [ '8.0', '8.1' ]
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: composer create-project nette/coding-standard temp/coding-standard --no-progress
      - run: cp ./.coding-standard/project.xml ./temp/nette-coding-standard/preset-sniffer/project.xml
      - run: cp ./.coding-standard/project.php ./temp/nette-coding-standard/preset-fixer/project.php
      - run: php temp/coding-standard/ecs check src tests --preset project
