name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request: null

jobs:
  tester:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0', '8.1' ]
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: vendor/bin/phpunit --exclude-group integration tests
      - name: "Coveralls.io"
        env:
          CI_NAME: github
          CI: true
          COVERALLS_REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.1/php-coveralls.phar
          php php-coveralls.phar --verbose --config tests/.coveralls.yml
